#!/bin/sh
set -e

cleanup () {
	/usr/share/libgcrypt20/clean-up-unmanaged-libraries \
		--bug-ref=984884 \
		"$@" \
		x86_64-linux-gnu \
		libgcrypt.so.20
}

if [ -n "$2" ] && ! cleanup; then
	echo "$0: Trying cleanup again with more logging..."
	cleanup --verbose
fi


